// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpmhwvouazwfemhbanco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwbWh3dm91YXp3ZmVtaGJhbmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODcwNjAsImV4cCI6MjA3MzI2MzA2MH0.OO7ApCzRu0vV3QyTG6MS1S4tDZ5o84h1cCXAUIymkac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});